# Generated by Django 6.0.6 on 2026-06-24 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeRepository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('desc', models.TextField(blank=True, verbose_name='描述')),
                ('system_prompt', models.TextField(blank=True, verbose_name='系统提示词')),
                ('image', models.ImageField(blank=True, null=True, upload_to='knowledge_repository/images/', verbose_name='图片')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifiedon', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.ForeignKey(blank=True, db_column='creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_repositories', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
                'db_table': 'dim_knowledge_repository',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='文件名')),
                ('type', models.CharField(blank=True, max_length=50, verbose_name='文件类型')),
                ('mime_type', models.CharField(blank=True, max_length=127, verbose_name='媒体类型')),
                ('filedata', models.FileField(upload_to='documents/files/', verbose_name='文件')),
                ('size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='文件大小')),
                ('chunk', models.BigIntegerField(default=0, verbose_name='分块数')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifiedon', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.ForeignKey(blank=True, db_column='creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('dim_knowledge_repository_id', models.ForeignKey(db_column='dim_knowledge_repository_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rag_app.knowledgerepository', verbose_name='知识库')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'db_table': 'dim_document',
            },
        ),
    ]
