# Generated by Django 6.0.6 on 2026-06-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_parsed',
            field=models.BooleanField(default=False, verbose_name='是否已解析'),
        ),
    ]
