# Generated by Django 6.0.6 on 2026-06-30 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0002_document_is_parsed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField()),
                ('message', models.JSONField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chat_message_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='会话描述')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifiedon', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.ForeignKey(blank=True, db_column='creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('dim_knowledge_repository_id', models.ForeignKey(db_column='dim_knowledge_repository_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='rag_app.knowledgerepository', verbose_name='知识库')),
            ],
            options={
                'verbose_name': '聊天会话',
                'verbose_name_plural': '聊天会话',
                'db_table': 'dim_chat_session',
            },
        ),
    ]
