"""
Django settings for Kaleido project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from Kaleido.environment import get_bool, get_env, get_int, get_list
from Kaleido.logger import setup_logger

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
setup_logger(BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env('DJANGO_SECRET_KEY', required=True)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_bool('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = get_list(
    'DJANGO_ALLOWED_HOSTS',
    default=('localhost', '127.0.0.1', '[::1]'),
)

SECURE_SSL_REDIRECT = get_bool('DJANGO_SECURE_SSL_REDIRECT', default=False)
SESSION_COOKIE_SECURE = get_bool('DJANGO_SESSION_COOKIE_SECURE', default=False)
CSRF_COOKIE_SECURE = get_bool('DJANGO_CSRF_COOKIE_SECURE', default=False)
SECURE_HSTS_SECONDS = get_int('DJANGO_SECURE_HSTS_SECONDS', default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = get_bool(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS',
    default=False,
)
SECURE_HSTS_PRELOAD = get_bool('DJANGO_SECURE_HSTS_PRELOAD', default=False)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'user',
    'rag_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Kaleido.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'static']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Kaleido.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': get_env('KALEIDO_DB_NAME', default='kaleido'),
        'USER': get_env('KALEIDO_DB_USER', default='postgres'),
        'PASSWORD': get_env('KALEIDO_DB_PASSWORD', required=True),
        'HOST': get_env('KALEIDO_DB_HOST', default='127.0.0.1'),
        'PORT': get_env('KALEIDO_DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'



REST_FRAMEWORK = {
    # 全局认证方式（所有接口默认需要 JWT 认证）
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # 全局权限控制（默认所有接口需要登录）
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# JWT 高级配置（可选）
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=4),  # Access Token 有效期
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Refresh Token 有效期
    'AUTH_HEADER_TYPES': ('Bearer',),                # 请求头中的 Token 前缀
}

CORS_ALLOW_CREDENTIALS = get_bool('DJANGO_CORS_ALLOW_CREDENTIALS', default=True)

CORS_ALLOW_ALL_ORIGINS = get_bool('DJANGO_CORS_ALLOW_ALL_ORIGINS', default=False)

CORS_ALLOWED_ORIGINS = get_list('DJANGO_CORS_ALLOWED_ORIGINS')

CORS_ALLOW_HEADERS = ('*')

# 允许前端读取流式接口返回的会话 ID
CORS_EXPOSE_HEADERS = ['X-Session-Id']

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

CSRF_TRUSTED_ORIGINS = get_list('DJANGO_CSRF_TRUSTED_ORIGINS')

# Celery 配置
# 使用 Redis 作为 Broker 和结果后端
CELERY_BROKER_URL = get_env(
    'KALEIDO_CELERY_BROKER_URL',
    default='redis://127.0.0.1:6379/0',
)
CELERY_RESULT_BACKEND = get_env(
    'KALEIDO_CELERY_RESULT_BACKEND',
    default=CELERY_BROKER_URL,
)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 29 * 60  # 软超时 29min，让任务有机会正常落终态
